### ISSUE TITLE
User Registration  

### ISSUE THREAD

**Issue by ayushkumar1610** [team-carpool/backend#4]
### Create an API for User Registration 
This API will be an endpoint for the [user registration component](https://github.com/team-carpool/frontend/issues/10).
The frontend will send JSON of Email, Name, and Password as a RequestBody.

Develop a User Model and UserRepository for the below User Data.

![User Model](https://user-images.githubusercontent.com/60136299/196756700-b40b4a57-8dde-41c5-8a09-41795528fc3c.png)

And develop a service that will consume UserRepository to save User Registration data to the database. 

Further Actions:

1. Start the development on the branch ```feature/signup```
2. Then test it locally
3. Then raise PR for it to merge in ```develop```

**Comment by team-carpool** [comment]
Backend User Registration's Endpoint URL:
```127.0.0.1:8080/users/signup```

**Comment by ayushkumar1610** [comment]
https://github.com/team-carpool/backend/pull/6
